//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISEKchatbot.Models
{
    public partial class undefined_defaults
    {
        public int id { get; set; }
        public int bot { get; set; }
        public string pattern { get; set; }
        public string replacement { get; set; }
    }
    
}
