//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISEKchatbot.Models
{
    public partial class bot
    {
        public int bot_id { get; set; }
        public string bot_name { get; set; }
        public string bot_desc { get; set; }
        public int bot_active { get; set; }
        public int bot_parent_id { get; set; }
        public string format { get; set; }
        public Nullable<int> use_aiml_code { get; set; }
        public int update_aiml_code { get; set; }
        public string save_state { get; set; }
        public int conversation_lines { get; set; }
        public int remember_up_to { get; set; }
        public int debugemail { get; set; }
        public int debugshow { get; set; }
        public int debugmode { get; set; }
        public string error_response { get; set; }
        public string default_aiml_pattern { get; set; }
    }
    
}
