//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISEKchatbot.Models
{
    public partial class myprogramo
    {
        public int id { get; set; }
        public string uname { get; set; }
        public string pword { get; set; }
        public string lastip { get; set; }
        public System.DateTime lastlogin { get; set; }
    }
    
}
