//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace ISEKchatbot.Models
{
    public partial class isekEntities : DbContext
    {
        public isekEntities()
            : base("name=isekEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aiml> aimls { get; set; }
        public DbSet<aiml_userdefined> aiml_userdefined { get; set; }
        public DbSet<botpersonality> botpersonalities { get; set; }
        public DbSet<bot> bots { get; set; }
        public DbSet<conversation_log> conversation_log { get; set; }
        public DbSet<myprogramo> myprogramoes { get; set; }
        public DbSet<page> pages { get; set; }
        public DbSet<spellcheck> spellchecks { get; set; }
        public DbSet<undefined_defaults> undefined_defaults { get; set; }
        public DbSet<unknown_inputs> unknown_inputs { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<wordcensor> wordcensors { get; set; }
    }
}
