//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISEKchatbot.Models
{
    public partial class aiml_userdefined
    {
        public int id { get; set; }
        public string aiml { get; set; }
        public string pattern { get; set; }
        public string template { get; set; }
        public int userid { get; set; }
        public int botid { get; set; }
        public System.DateTime date { get; set; }
    }
    
}
