//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISEKchatbot.Models
{
    public partial class aiml
    {
        public int id { get; set; }
        public int bot_id { get; set; }
        public string aiml1 { get; set; }
        public string pattern { get; set; }
        public string thatpattern { get; set; }
        public string template { get; set; }
        public string topic { get; set; }
        public string filename { get; set; }
        public string php_code { get; set; }
    }
    
}
