//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISEKchatbot.Models
{
    public partial class user
    {
        public int id { get; set; }
        public string name { get; set; }
        public string session_id { get; set; }
        public int bot_id { get; set; }
        public int chatlines { get; set; }
        public string ip { get; set; }
        public string referer { get; set; }
        public string browser { get; set; }
        public System.DateTime date_logged_on { get; set; }
        public System.DateTime last_update { get; set; }
        public string state { get; set; }
    }
    
}
