//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ISEKchatbot.Models
{
    public partial class conversation_log
    {
        public int id { get; set; }
        public string input { get; set; }
        public string response { get; set; }
        public int userid { get; set; }
        public int bot_id { get; set; }
        public System.DateTime timestamp { get; set; }
    }
    
}
